---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

From January 1-15, 2024, I visited Costa Rica as a class trip. I conducted an observational study on foraging behavior of leafcutter ants. My goal was to assess qualities of leaves that are rejected far from the colony, vs. leaves that are carried all the way to the colony entrance and rejected at the doorstep. I also conducted a behavioral analysis to understand the sequence of events that occur when a leaf is rejected by the ants.

Leafcutter ants are known for their characteristic behavior of cutting leaves from trees and carrying them back to their colonies. Then, they use the leaves as fertilizer for a fungus that they grow like farmers growing crops. The ant larvae feed on the fungus.  The ants can detect chemical signals from the fungus and change their foraging behavior to meet the fungus's needs.

When we arrived at CCI, I noticed that there were a lot of leaves dropped right outside the colony, but few leaves dropped down the ant trail. I was curious why the ants would expend energy carrying leaves all the way back only to reject them right outside the door.  I surmised that they must be gaining some new information about the leaves near the colony.
