---
title: "Leaf Analysis"
author: "Jaxson Freund"
date: "2024-05-06"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
  markdown: 
    wrap: 72
---

# Measurements taken:

-   leaf fragments per quadrat

-   total leaf mass (grams) per quadrat

-   surface area of each leaf fragment

# Leaf Area Analysis

Packages used:

-   tidyverse

-   ggplot2

-   ggforce

-   readxl

-   agricolae

-   purrr

-   dplyr

-   openxlsx

-   ggdisst

-   scales

```{R, echo=FALSE, include=FALSE}
library(tidyverse)
library(readxl)
library(ggplot2)
library(ggforce)
library(dplyr)
library(agricolae)
library(purrr)
library(openxlsx)
library(ggdist)
library(scales)

df <- read_xlsx("~/Desktop/Spring 2024/Field Ecology Lab/Leafcutters Jan 2024/Excel Sheets/No statistics.xlsx")

df_long <- tidyr::gather(df, key = "Distance", value = "Area")

df_long$Distance <- as.character(df_long$Distance)

df_long_nona <- df_long[complete.cases(df_long$Area), ]

df_long_nona$Distance <- as.character(df_long_nona$Distance)

df_long_nona$Distance <- factor(df_long_nona$Distance, levels = unique(df_long_nona$Distance))
```

```{R, echo=FALSE, include=FALSE}
na.omit(df_long_nona)
model <- aov(Area ~ Distance, data = df_long_nona)
```

```{R, echo = FALSE}
tukey_results <- HSD.test(model, "Distance")
tukey_df <- as.data.frame(tukey_results$groups)
significant_comparisons <- tukey_df[tukey_df$`p adj` < 0.05, ]
significant_groups <- unique(c(significant_comparisons$group1, significant_comparisons$group2))

```

## Visualize the Leaf Area Data
### Box-and Whisker Plot
```{R, echo = FALSE}
# box  and whisker
ggplot(df_long_nona, aes(x = Distance, y = Area)) +
  geom_boxplot() +
  labs(title = "",
       x = "Distance from Colony Main Entrance (m)",
       y = "Leaf Surface Area (cm^2)") +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "white"),
        panel.grid.major.x = element_line(color = "white"))+
  scale_y_continuous(breaks = seq(0, max(df_long_nona$Area), by = 0.5))
```

### Scatter Plot
```{R, echo = FALSE, include = FALSE}
# scatter w/ jitter
ggplot(df_long_nona, aes(x = Distance, y = Area)) +
  geom_point(position = position_jitter(width = 0.1, height = 0.1), color = "darkgreen", alpha = 0.1) +
  labs(title = "",
       x = "Distance from Colony Main Entrance (m)",
       y = "Leaf Surface Area (cm^2)") +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "white"),
        panel.grid.major.x = element_line(color = "white")) +
  scale_y_continuous(breaks = seq(0, max(df_long_nona$Area), by = 0.5))
```

```{R, echo = FALSE, include = FALSE}
# violin plot
ggplot(df_long_nona, aes(x = Area, y = Distance)) +
  geom_violin() +
  geom_sina(color = "green4", alpha = 0.5) +  
  labs(title = "",
       x = "Leaf Surface Area (cm^2)",
       y = "Distance from Colony Main Entrance (m)") +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "white"),
        panel.grid.major.y = element_line(color = "white")) +
  scale_x_continuous(breaks = seq(0, max(df_long_nona$Area), by = 0.5)) +
  coord_flip()
```

```{R, echo = FALSE}
ggplot(df_long_nona, aes(x = Area, y = Distance)) +
  geom_violin() +
  geom_sina(color = "green4", alpha = 0.5) +
  stat_summary(
    fun.data = "mean_cl_normal",
    geom = "point",
    color = "black",
    size = 2.5,
    position = position_nudge(x = 0.15)
  ) +
  labs(
    title = "",
    x = expression("Surface Area (cm"^2*")"),
    y = "Distance (m)"
  ) +
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid = element_line(color = "white"),
    panel.grid.major.y = element_line(color = "white")
  ) +
  scale_x_continuous(breaks = seq(0, max(df_long_nona$Area), by = 0.5)) +
  coord_flip() 
 
```

### Bar Chart
```{R, echo = FALSE}
# bar chart
summary_data <- df_long_nona %>%
  group_by(Distance) %>%
  summarize(Mean = mean(Area, na.rm = TRUE),
            SE = sd(Area, na.rm = TRUE) / sqrt(sum(!is.na(Area))))

ggplot(summary_data, aes(x = Distance, y = Mean, fill = factor(Distance))) +
  geom_bar(stat = "identity", position = "dodge", fill = ifelse(summary_data$Distance == "0", "firebrick3", "darkslategray4")) +
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE), position = position_dodge(width = 0.8), width = 0.25) +
  labs(title = "",
       x = "Distance from Colony Main Entrance (m)",
       y = "Leaf Surface Area (cm^2)") +
  theme(legend.position = "none",
        panel.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "white"),
        panel.grid.major.x = element_line(color = "white"))
```

## Statistics
```{R, echo=FALSE, include=FALSE}
na.omit(df_long_nona)
model <- aov(Area ~ Distance, data = df_long_nona)
```

### Summary Stats and Significant Groups
```{R, echo=FALSE}
tukey_results <- HSD.test(model, "Distance")
print(tukey_results)
```

Only meter 20 was sigificant, but if an outlier leaf fragment is removed, there is no significant difference in surface area.

# Leaf Quantity Analysis
```{R, echo = FALSE, include = FALSE}
df <- read_xlsx("~/Desktop/Spring 2024/Field Ecology Lab/Leafcutters Jan 2024/Excel Sheets/No statistics.xlsx")


df_long <- tidyr::gather(df, key = "Distance", value = "Area")

df_long$Distance <- as.character(df_long$Distance)

df_long_nona <- df_long[complete.cases(df_long$Area), ]

df_long_nona$Distance <- as.character(df_long_nona$Distance)

df_long_nona$Distance <- factor(df_long_nona$Distance, levels = unique(df_long_nona$Distance))

summary_data <- df_long_nona %>%
  group_by(Distance) %>%
  summarize(Mean = mean(Area, na.rm = TRUE),
            SE = sd(Area, na.rm = TRUE) / sqrt(sum(!is.na(Area))))
area_vector <- summary_data$Mean
distance_vector <- summary_data$Distance

mass_count_excel_file_path <- "~/Desktop/Spring 2024/Field Ecology Lab/Leafcutters Jan 2024/Excel Sheets/Area Data.xlsx"

df_excel <- read_excel(mass_count_excel_file_path)

leaf_count_row <- df_excel[2, ]
count_vector <- as.vector(unlist(leaf_count_row))
count_vector <- count_vector[count_vector != "count"]
count_vector <- count_vector[count_vector != "1554"]
count_vector <- as.numeric(count_vector)


leaf_mass_row <- df_excel[1, ]
mass_vector <- as.vector(unlist(leaf_mass_row))
mass_vector <- mass_vector[mass_vector != "mass"]
mass_vector <- mass_vector[mass_vector != "39.5"]
mass_vector <- as.numeric(mass_vector)

mass_per_leaf <- mass_vector / count_vector

mass_per_area <- mass_vector / area_vector / count_vector  
```

## Summary of Data
```{R, echo=FALSE}
quadrat_data <- data.frame(
  Distance = distance_vector,
  Area = area_vector,
  Mass = mass_vector,
  Count = count_vector,
  MperL = mass_per_leaf,
  MperA = mass_per_area
)
colnames(quadrat_data) <-
c("Distance (m)", "Avg Area (cm²)", "Mass (g)", "Count","g/leaf", "g/cm²")
print(quadrat_data, row.names = FALSE)
```

```{R, echo=FALSE}
x <- 0:23
y <- mass_vector[-(1:2)]
z <- count_vector[-(1:2)]
ar <- area_vector[-(1:2)]
ml <- mass_per_leaf[-(1:2)]
ma <- mass_per_area[-(1:2)]

df_quadrat <- data.frame(
  x = x,
  y = y,
  z = z,
  ar = ar,
  ml = ml,
  ma = ma
)
```

## Visualize Data
### Plot Leaf Count and Mass vs. Distance from Colony
```{R, echo =FALSE}
par(mar = c(5, 4, 4, 2) + 0.1, oma = c(0, 0, 0, 1))
plot(x, y, type = "p", col = "#298c8c", pch = 16, ylab = "", xlab = "Distance (m)", axes = TRUE)

mtext("Mass (g)", side = 2, line = 2, col = "#298c8c", cex = 1.2)  

fit <- lm(log(y) ~ x)


x_pred <- seq(min(x), max(x), length.out = 100)
y_pred <- exp(predict(fit, newdata = data.frame(x = x_pred)))

lines(x_pred, y_pred, col = "#298c8c", type = "l")

par(new = TRUE)
plot(x, z, type = "p", col = "#f1a226", pch = 16, ylab = "", xlab = "", axes = FALSE)

fit <- lm(log(z) ~ x)


x_pred <- seq(min(x), max(x), length.out = 100)
z_pred <- exp(predict(fit, newdata = data.frame(x = x_pred)))
lines(x_pred, z_pred, col = "#f1a226", type = "l")

mtext("Count", side = 4, line = 2, col = "#f1a226", cex = 1.2)  

axis(4, col = "black", col.axis = "black", las = 1)  

legend("topright", legend = c("Mass (g)", "Count"), col = c("#298c8c", "#f1a226"), pch = 16)
```
This data supports my initial observation that significantly more leaf fragments are dropped outside of the colony vs. farther down the leafcutter path. Both trends are significant.

### Plot Leaf Count vs. Mass
```{R, echo=FALSE}
plot(z, y, main = "", xlab = "Count", ylab = "Mass (g)", col = "maroon", pch = 16)

fit <- lm(log(y) ~ z)


z_pred <- seq(min(z), max(z), length.out = 100)
y_pred <- exp(predict(fit, newdata = data.frame(z = z_pred)))

lines(z_pred, y_pred, col = "maroon", type = "l")

a <- exp(coef(fit)[1])
b <- coef(fit)[2]
eq <- sprintf("y=0.29e^(0.02x)")
text(3, max(y), eq, pos = 4, col = "black", cex = 0.8)
```
Leaf count and mass are significantly correlated.  Interestingly, the trend is not linear, suggesting that where more leaves are dropped, they have on average more mass per leaf. Since the average surface area didn't differ between quadrats, this suggests that where more leaves are dropped, they are either thicker or denser.  Also interestingly, since the data doesn't show a trend of changing leaf area with distance, it seems that leaf density/thickness is a selection factor, but that it is a constant factor. They are equally likely to reject a leaf based on density/thickness anywhere along the transect.


## Plot Mass per Leaf vs. Distance
```{R, echo=FALSE}
df_4 <- data.frame(
  x = distance_vector,
  ar = area_vector,
  ml = mass_per_leaf,
  ma = mass_per_area
)

df_4$x <- as.numeric(as.character(df_4$x))

# Fit a linear regression model
model <- lm(ml ~ x, data = df_4)

# Create a scatter plot
plot(df_4$x, df_4$ml, main = "Mass per Leaf vs. Distance from Main Colony Entrance", xlab = "Distance (m)", ylab = "Mass per Leaf", col = "purple", pch = 16)

# Add the line of best fit to the plot
abline(model, col = "purple")

# Extract coefficients
coefficients <- coef(model)

# Add the equation of the line
equation <- paste("ml =", round(coefficients[1], 2), "+", round(coefficients[2], 2), "* x")
text(min(df_4$x), max(df_4$ml), equation, pos = 4, col = "purple")

# Calculate R-squared
r_squared <- summary(model)$r.squared

# Add R-squared value to the plot
r_squared_text <- paste("R-squared =", round(r_squared, 3))
text(min(df_4$x), max(df_4$ml) - 0.1 * diff(range(df_4$ml)), r_squared_text, pos = 4, col = "black")
```
There is no trend in mass/leaf along the transect, supporting the theory that leaf density/thickness is a constant selection filter.

# Conclusions
The data supports my observations that there are significantly more leaf fragments rejected closer to the colony.  However, based on my data, leaf size is not a significantly greater factor near the colony vs. far from the colony.  I am not able to explore other potential selection factors based on this data.  However, based on previous research about leafcutter ants, I believe they may reject leaf fragments based on chemical signals. Leafcutter ants can detect chemical signals from the fungi they farm, so perhaps they can also use chemical signals to evaluate the leaf fragments. 

For more information on near-colony leaf-rejection eveents, see my [behavioral analysis](behavior.html).

